version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - app-network
    ports:
      - "3005:3005"
    volumes:
    - ./app:/home/app
    depends_on:
      - db

  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wizard
      MYSQL_USER: wizard
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - app-network
    expose:
      - "3306"
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
    
volumes:
  app: {}
  db-data: {}

networks:
  app-network:
    driver: bridge