version: "3"
services:

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    networks:
      - app-network
    # expose:
    #   - "3005"
    # ports:
    #   - 3005:3005
    volumes:
    - ./api:/home/api
    depends_on:
      - db

  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wizard
      MYSQL_USER: wizard
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - app-network
    expose:
      - "3306"
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network

  # front:
  #   build:
  #     context: .
  #     dockerfile: front.Dockerfile
  #   networks:
  #     - app-network
  #   expose:
  #     - "3000"
  #   volumes:
  #   - ./front:/home/front

  vue:
    build:
      context: .
      dockerfile: vue.Dockerfile
    networks:
      - app-network
    volumes:
    - ./vue:/home/vue
    command:
      bash -c "npm i && npm run serve"

  web:
    image: nginx:mainline-alpine
    ports:
      - "88:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      
    depends_on:
      - api
      # - front
      - vue
    networks:
      - app-network
    
volumes:
  app: {}
  front: {}
  db-data: {}
  vue: {}

networks:
  app-network:
    driver: bridge